/*global angular */

angular.module('mathSkills').service('data26_2', ['dataUtils', function (dataUtils) {
    var desc = {
			title: '26.2 Conversion between the Fahrenheit and Celsius Temperature Scales',
    		path: '26.2-conversion-between-fahrenheit-and-celsius',
            children: []
        },
	        template = {
			
			flexy: {
                title: '26.2 Conversion between the Fahrenheit and Celsius Temperature Scales',
                children: [{
                    title: 'Main Answer',
                    children: [{
						problem: '\\pan{4}{8}'
									+'{$modalChart}',
						answer: '\\grp'
									+'{$solution}',
						controls: {
								"checkAnswer": true,
								"help": '\\rowgrp' 	 
											+'$firstTable'
											+'{\\html{&nbsp;}}'
											+'{\\html{&nbsp;}}'
											+'{css'
												+'{\\grp'
													+'{\\str{Answer: &nbsp;}}'
													+'{$helpAnswer}'
												+'}'
												+'{help-answer-text}'
											+'}'
											+'{\\html{&nbsp;}}',
						}
					}]
				}]
			}
        },
        data = [
				{	// problem 1
					ansNumber: '212',
					solution: dataUtils.pre(
									'\\grp'
										+'{\\html{100&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
								),
					problem: dataUtils.pre(
								'\\css'
									+'{\\grp'
										+'{\\html{100&deg; C =}}'
										+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
										+'{\\str{ F}}'
									+'}'
									+'{blue-text}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{$$problem}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( 100 ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( 100 ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 180 + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 212}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 2
					ansNumber: '0',
					solution: dataUtils.pre(
									'\\grp'
										+'{\\html{32&deg; F =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; C}}'
								),
					problem: dataUtils.pre(
								'\\css'
									+'{\\grp'
										+'{\\html{32&deg; F =}}'
										+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
										+'{\\str{ C}}'
									+'}'
									+'{blue-text}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{$$problem}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( 32 - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( 32 - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( 0 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = 0}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 3
					ansNumber: '68',
					probNumber: '20',
					solution: dataUtils.pre(
									'\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
								),
					problem: dataUtils.pre(
								'\\css'
									+'{\\grp'
										+'{\\html{$probNumber&deg; C =}}'
										+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
										+'{\\str{ F}}'
									+'}'
									+'{blue-text}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{$problem}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 36 + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$ansNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 4
					ansNumber: '46',
					probNumber: '8',
					addedNumbers: '14.4',
					helpAnsNumber: '46.4',
					roundText: 'Round answer to the nearest whole degree F.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; C =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ F}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$addedNumbers + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$helpAnsNumber}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 5
					ansNumber: '95',
					probNumber: '35',
					addedNumbers: '63',
					helpAnsNumber: '63',
					roundText: '',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; C =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ F}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$addedNumbers + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$helpAnsNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 6
					ansNumber: '64',
					probNumber: '18',
					addedNumbers: '32.4',
					helpAnsNumber: '64.4',
					roundText: 'Round answer to the nearest whole degree F.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; C =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ F}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$addedNumbers + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$helpAnsNumber}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 7
					ansNumber: '10',
					probNumber: '50',
					resultNumber: '18',
					solution: dataUtils.pre(
									'\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; C}}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = $$ansNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 8
					ansNumber: '30',
					probNumber: '86',
					resultNumber: '54',
					solution: dataUtils.pre(
									'\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; C}}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = $$ansNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 9
					ansNumber: '6',
					probNumber: '42',
					resultNumber: '10',
					helpAnsNumerator: '50',
					helpAnswerNumber: '5.555...', 
					roundText: 'Round answer to the nearest whole degree C.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; C}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{$$helpAnsNumerator}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{or&nbsp; $$helpAnswerNumber}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 10
					ansNumber: '42',
					probNumber: '107',
					resultNumber: '75',
					helpAnsNumerator: '375',
					helpAnswerNumber: '41.666...', 
					roundText: 'Round answer to the nearest whole degree C.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; C}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{$$helpAnsNumerator}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{or&nbsp; $$helpAnswerNumber}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 11
					ansNumber: '1832',
					probNumber: '1000',
					resultNumbers: '1800',
					helpAnsNumber: '1832',
					roundText: '',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; C =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ F}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$resultNumbers + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$helpAnsNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$ansNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 12
					ansNumber: '90032',
					probNumber: '50,000',
					resultNumbers: '90,000',
					helpAnsNumber: '90,032',
					roundText: '',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; C =}}'
										+'{\\input{$$ansNumber}}'
										+'{\\str{&deg; F}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; C =}}'
												+'{\\html{<span class=bottomBluePadded>&nbsp; ? &nbsp;</span>&deg;}}'
												+'{\\str{ F}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Fahrenheit temperature, so use the <br>\"F =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( C ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Multiply:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = 1.8 ( $$probNumber ) + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & add:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$resultNumbers + 32}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width120}'
											+'}'
											+'{\\grp'
												+'{\\str{F = $$helpAnsNumber}}'
											+'}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
												+'{\\str{$$helpAnsNumber&deg;}}'
												+'{\\str{ F}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 13
					ansWhole: '26',
					ansNumerator: '1',
					probNumber: '79',
					resultNumber: '47',
					helpAnsNumerator: '235',
					roundText: 'Give answer as a mixed number.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\css'
											+'{\\mixed'
												+'{\\input{$$ansWhole}}'
												+'{\\frac'
													+'{\\input{$$ansNumerator}}'
													+'{\\input{9}}'
												+'}'
											+'}'
											+'{}'
										+'}'
										+'{\\str{&deg; C}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{?}}'
														+'{\\str{?}}'
													+'}'
													+'{fracNoMargin blue-text}'
												+'}'
												+'{\\str{&deg;&nbsp; C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{$$helpAnsNumerator}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
											  	+'{\\css'
													+'{\\mixed'
														+'{\\str{$$ansWhole}}'
														+'{\\frac'
															+'{\\str{$$ansNumerator}}'
															+'{\\str{9}}'
														+'}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{&deg;&nbsp; C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
				,
				{	// problem 14
					ansWhole: '37',
					ansNumerator: '7',
					probNumber: '100',
					resultNumber: '68',
					helpAnsNumerator: '340',
					roundText: 'Give answer as a mixed number.',
					solution: dataUtils.pre(
								'\\rowgrp'
									+'{\\str{$$roundText}}'
									+'{\\html{&nbsp;}}'
									+'{\\grp'
										+'{\\html{$$probNumber&deg; F =}}'
										+'{\\css'
											+'{\\mixed'
												+'{\\input{$$ansWhole}}'
												+'{\\frac'
													+'{\\input{$$ansNumerator}}'
													+'{\\input{9}}'
												+'}'
											+'}'
											+'{}'
										+'}'
										+'{\\str{&deg; C}}'
									+'}'
								),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\css'
											+'{\\grp'
												+'{\\html{$$probNumber&deg; F =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{?}}'
														+'{\\str{?}}'
													+'}'
													+'{fracNoMargin blue-text}'
												+'}'
												+'{\\str{&deg;&nbsp; C}}'
											+'}'
											+'{blue-text}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We are converting to a Celsius temperature, so use the<br>\"C =\" formula.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Formula:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( F - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Substitute:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Solve by following the order of operations.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Parenthesis:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$probNumber - 32 )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result & multiply:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C =}}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{5}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{( $$resultNumber )}}'
											+'}'
										+'}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Result:}}'
												+'{width140}'
											+'}'
											+'{\\grp'
												+'{\\str{C = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\str{$$helpAnsNumerator}}'
														+'{\\str{9}}'
													+'}'
													+'{fracNoMargin}'
												+'}'
											+'}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{$$roundText}}'
								),
					helpAnswer: dataUtils.pre(
											  '\\grp'
											  	+'{\\css'
													+'{\\mixed'
														+'{\\str{$$ansWhole}}'
														+'{\\frac'
															+'{\\str{$$ansNumerator}}'
															+'{\\str{9}}'
														+'}'
													+'}'
													+'{fracNoMargin}'
												+'}'
												+'{\\str{&deg;&nbsp; C}}'
						),
					modalChart: dataUtils.pre('\\html'
								+'{<table class=equivalence-table>'
									+'<th colspan="4">Equivalence Table</th>'
									+'<tr>'
										+'<td>F</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>1.8</td>'
										+'<td>( C ) + 32</td>'
									+'</tr>'
									+'<tr>'
										+'<td>C</td>'
										+'<td>&nbsp;=&nbsp;</td>'
										+'<td>'
											+'<table class=inside-equivalence-table>'
												+'<tr>'
													+'<td>5</td>'
												+'</tr>'
												+'<tr>'
													+'<td></td>'
												+'</tr>'
												+'<tr>'
													+'<td>9</td>'
												+'</tr>'
											+'</table>'
										+'</td>'
										+'<td class=td-inside-equivalence-table>'
											+'(F - 32)'
										+'</td>'
									+'</tr>'
								+'</table>}'
							),
					template: 'flexy',
				}
        ];
		shuffle = [
				{ problems: [1], total: 1},
				{ problems: [2], total: 1},
				{ problems: [3,4,5,6], total: 2},
				{ problems: [7,8], total: 1},
				{ problems: [9,10], total: 1},
				{ problems: [11,12], total: 1},
				{ problems: [13,14], total: 1}
		];
    
    	return dataUtils.build(desc, template, data, shuffle);
		
		//return dataUtils.build(desc, template, data);
}]);


