/*global angular */

angular.module('mathSkills').service('data24_2', ['dataUtils', function (dataUtils) {
    var desc = {
			title: '24.2 Add, Subtract, Multiply, and Divide English Measurements',
            path: '24.2-add-subtract-multiply-divide-english-measurements',
            children: []
        },
	        template = {
			// first template, integers operation
			oneConversion: {
                title: 'Evaluating Algebraic Expressions',
                children: [{
                    title: 'Main Answer',
                    children: [{
						problem: '$stateProblem',
						answer: '$solution',
						controls: {
								"checkAnswer": true,
								"help": '\\rowgrp'
											+'$firstLines'
											+'{\\html{&nbsp;}}'
											+'{css'
												+'{\\grp'
													+'{\\str{Answer: &nbsp;}}'
													+'{$helpAnswer}'
												+'}'
												+'{help-answer-text}'
											+'}'
											+'{\\html{&nbsp;}}',
								"modalButton": "\\html{Equivalence Chart}",
								"modalText": '$modalChart',
								"modalClass": 'modalMiddleLeft',
								"fixHelpControls": true,
						}
					}]
				}]
			}
        },
        data = [
			// problem 1
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Solve and give the answer in simplified measurements. }}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\html{'
											+'<table>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td>'
														+'10 lbs'
													+'</td>'
													+'<td>'
														+'12 oz.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'&nbsp;&nbsp;3 lbs.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'&nbsp;&nbsp;9 oz.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '14',
				firstField: 'lbs.',
				secondAnswer: '5',
				secondField: 'oz.',
				firstLines: dataUtils.pre(
									'{\\str{<u>First</u> add up all the same measurements.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
											+'<table>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td>'
														+'10 lbs.'
													+'</td>'
													+'<td>'
														+'12 oz.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'&nbsp;&nbsp;3 lbs.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'&nbsp;&nbsp;9 oz.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td class=divisionPadTop>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'13 lbs.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'21 oz.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{<u>Second</u>, simplify as necessary. Remember to always start with the smallest unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{21 oz. can be simplified because it is more than the 16 oz. that make a pound.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 21 oz. by 16 to find out how many \"ounces\" are in 21 pounds.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>1 lb.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>16</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>21&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>16</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>5 oz. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{21 oz. is the same as 1 lb. 5 oz.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;13 lbs.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>21 oz.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;1 lb.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;5 oz.'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;14 lbs.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;5 oz.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The measurements are simplified. We are done.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>16 oz</td><td>=</td><td>1 lb</td></tr><tr><td>2000 lbs</td><td>=</td><td>1 ton</td></tr></table>}'),
				template: 'oneConversion'
			}
			,
			// problem 2
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Solve and give the answer in simplified measurements. }}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\html{'
											+'<table>'
												+'$$problemTableRows'
											+'</table>'
										+'}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '7',
				firstField: 'gal.',
				secondAnswer: '1',
				secondField: 'qt.',
				problemTableRows: '<tr>'
									+'<td>'
										+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
									+'</td>'
									+'<td>'
										+'2 gal.'
									+'</td>'
									+'<td>'
										+'&nbsp;2 qt.'
									+'</td>'
								+'</tr>'
								+'<tr>'
									+'<td>'
										+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
									+'</td>'
									+'<td class=bottomBlackPadded>'
										+'4 gal.'
									+'</td>'
									+'<td class=bottomBlackPadded>'
										+'&nbsp;3 qt.'
									+'</td>'
								+'</tr>',
				firstLines: dataUtils.pre(
									'{\\str{<u>First</u> add up all the same measurements.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
											+'<table>'
												+'$$problemTableRows'
												+'<tr>'
													+'<td class=divisionPadTop>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'6 gal.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'&nbsp;5 qt.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{<u>Second</u>, simplify as necessary. Remember to always start with the smallest unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{5 qt. can be simplified because it is more than the 4 qt. that make a pound.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 5 qt. by 4 to find out how many \"gallons\" are in 5 qt.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;</span>1 gal.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>4</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>5&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>4</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>1 qt. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{5 qt. is the same as 1 gal. 1 qt.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;6 gal.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>&nbsp;&nbsp;5 qt.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;1 gal.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;1 qt.'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;7 gal.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;1 qt.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The measurements are simplified. We are done.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>3 tsp</td><td>=</td><td>1 tbsp</td></tr><tr><td>2 tbsp</td><td>=</td><td>1 fl oz</td></tr><tr><td>8 fl oz</td><td>=</td><td>1 c</td></tr><tr><td>2 c</td><td>=</td><td>1 pt</td></tr><tr><td>2 pt</td><td>=</td><td>1 qt</td></tr><tr><td>4 qt</td><td>=</td><td>1 gal</td></tr></table>}'),
				template: 'oneConversion'
			}
			,
			// problem 3
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Solve and give the answer in simplified measurements. }}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\str{(&nbsp;4 hr. &nbsp;45 min.) &nbsp;+&nbsp; (&nbsp;3 hr. &nbsp;50 min.)}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '8',
				firstField: 'hrs.',
				secondAnswer: '35',
				secondField: 'min.',
				firstLines: dataUtils.pre(
									'{\\str{<u>First</u> add up all the same measurements.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
											+'<table>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td>'
														+'4 hrs'
													+'</td>'
													+'<td>'
														+'45 min.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'3 hrs.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'50 min.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td class=divisionPadTop>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'7 hrs.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'95 min.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{<u>Second</u>, simplify as necessary. Remember to always start with the smallest unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{95 min. can be simplified because it is more than the 60 min. that make an hour.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 95 min. by 60 to find out how many \"hours\" are in 95 min. }}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>1 hr.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>60</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>95&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>60</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>35 min. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{95 min. is the same as 1 hr. 35 min.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;7 hrs.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>95 min.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;1 hr.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'35 min.'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;8 hr.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'35 min.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The measurements are simplified. We are done.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>60 sec</td><td>=</td><td>1 min</td></tr><tr><td>60 min</td><td>=</td><td>1 hr</td></tr><tr><td>24 hr</td><td>=</td><td>1 day</td><tr><td>7 days</td><td>=</td><td>1 wk</td></tr></table>}'),
				template: 'oneConversion'
			}
			,
			// problem 4
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Solve and give the answer in simplified measurements. }}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\str{(&nbsp;2 ft. &nbsp;8 in.) &nbsp;+&nbsp; (&nbsp;3 ft. &nbsp;7 in.)}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '6',
				firstField: 'ft.',
				secondAnswer: '3',
				secondField: 'in.',
				firstLines: dataUtils.pre(
									'{\\str{<u>First</u> add up all the same measurements.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'

											+'<table>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td>'
														+'2 ft.'
													+'</td>'
													+'<td>'
														+'&nbsp;&nbsp;8 in.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'3 ft.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'&nbsp;&nbsp;7 in.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td class=divisionPadTop>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'5 ft.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'15 in.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{<u>Second</u>, simplify as necessary. Remember to always start with the smallest unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{15 in. can be simplified because it is more than the 12 in. that make a foot.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 15 in. by 12 to find out how many \"feet\" are in 15 in.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>1 ft.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>12</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>15&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>12</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>&nbsp;&nbsp;3 in. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{15 in. is the same as 1 ft. 3 in.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;5 ft.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>15 in.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;1 ft.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;3 in.'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;6 ft.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;3 in.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The measurements are simplified. We are done.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>12 in</td><td>=</td><td>1 ft</td></tr><tr><td>3 ft</td><td>=</td><td>1 yd</td></tr><tr><td>5,280 ft</td><td>=</td><td>1 mi</td></tr></table>}'),
				template: 'oneConversion'
			}
			,
			// problem 5
			{	
				stateProblem: dataUtils.pre(
									'\\pan{5}{7}'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{Solve and give the answer in simplified measurements. }}'
											+'}'
											+'{\\str{&nbsp;}}'
											+'{\\str{(&nbsp;15 hr. &nbsp;36 min. &nbsp;45 sec.) &nbsp;+&nbsp; (&nbsp;4 hr. &nbsp;40 min. &nbsp;50 sec.)}}'
										+'}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
									+'{\\input{$$thirdAnswer}}'
									+'{\\str{&nbsp;$$thirdField}}'
								+'}'
					),
				firstAnswer: '20',
				firstField: 'hrs.',
				secondAnswer: '17',
				secondField: 'min.',
				thirdAnswer: '35',
				thirdField: 'sec.',
				firstLines: dataUtils.pre(
									'{\\str{<u>First</u> add up all the same measurements.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
											+'<table>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td>'
														+'15 hrs'
													+'</td>'
													+'<td>'
														+'36 min.'
													+'</td>'
													+'<td>'
														+'45 sec.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>+</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'4 hrs.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'40 min.'
													+'</td>'
													+'<td class=bottomBlackPadded>'
														+'50 sec.'
													+'</td>'
												+'</tr>'
												+'<tr>'
													+'<td class=divisionPadTop>'
														+'&nbsp;&nbsp;&nbsp;<span class=fontsize110>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'19 hrs.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'76 min.'
													+'</td>'
													+'<td class=divisionPadTop>'
														+'95 sec.'
													+'</td>'
												+'</tr>'
											+'</table>'
										+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{<u>Second</u>, simplify as necessary. Remember to always start with the smallest unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{95 sec. can be simplified because it is more than the 60 sec. that make a minute.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 95 sec. by 60 to find out how many \"minutes\" are in 95 sec.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>1 min.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>60</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>95&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>60</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>35 sec. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{95 sec. is the same as 1 min. 35 sec.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table class=label_like>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;19 hrs.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;76 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>95 sec.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;1 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'35 sec.'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=6>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;19 hr.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;77 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'35 sec.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Now 77 minutes can be simplified because it is more than the 60 minutes that make an hour. }}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Divide 77 minutes by 60 to find out how many \"hours\" are in 77 minutes. }}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>1 hr.'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>60</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>77&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>60</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>17 min. (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{77 min. is the same as 1 hr. 17 min.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table class=label_like>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;19 hrs.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;77 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;<span class=line_through>35 sec.</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;1 hr.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;17 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=borderTopBlue>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=2>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;20 hr.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;17 min.'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;35 sec.'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The measurements are simplified. We are done.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField&nbsp;&nbsp;$$thirdAnswer&nbsp;$$thirdField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>60 sec</td><td>=</td><td>1 min</td></tr><tr><td>60 min</td><td>=</td><td>1 hr</td></tr><tr><td>24 hr</td><td>=</td><td>1 day</td><tr><td>7 days</td><td>=</td><td>1 wk</td></tr></table>}'),
				template: 'oneConversion'
			}
			
        ];
		/*shuffle = [
				{ problems: [1,2], total: 1},
				{ problems: [3,4], total: 1},
				{ problems: [5,6], total: 1},
				{ problems: [7,8], total: 1},
				{ problems: [9,10], total: 1},
				{ problems: [11,12], total: 1},
				{ problems: [13,14], total: 1},
				{ problems: [15,16], total: 1},
				{ problems: [17,18], total: 1},
				{ problems: [19,20], total: 1}
		];
    
    	return dataUtils.build(desc, template, data, shuffle);*/
		
		return dataUtils.build(desc, template, data);
}]);
