/*global angular */

angular.module('mathSkills').service('data24_1', ['dataUtils', function (dataUtils) {
    var desc = {
			title: '24.1 Simplifying English Measurements',
    		path: '24.1-simplifying-english-measurements',
            children: []
        },
	        template = {
			// first template, integers operation
			flexy: {
                title: 'Evaluating Algebraic Expressions',
                children: [{
                    title: 'Main Answer',
                    children: [{
						problem: '$stateProblem',
						answer: '$solution',
						controls: {
								"checkAnswer": true,
								"help": '\\rowgrp'
											+'$firstLines'
											+'{\\html{&nbsp;}}'
											+'{css'
												+'{\\grp'
													+'{\\str{Answer: &nbsp;}}'
													+'{$helpAnswer}'
												+'}'
												+'{help-answer-text}'
											+'}'
											+'{\\html{&nbsp;}}',
								"modalButton": "\\html{Equivalence Chart}",
								"modalText": '$modalChart',
								"modalClass": 'modalMiddleLeft',
								"fixHelpControls": true,
						}
					}]
				}]
			}
        },
        data = [
			// problem 1
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; 140 minutes.}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '2',
				firstField: 'hr.',
				secondAnswer: '20',
				secondField: 'min.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 60 minutes = 1 hour. 140 minutes is more units than make the next larger time measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 140 minutes by 60 to find out how many \"hours\" are in 140 minutes.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;</span>2 hours'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>60</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>140&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>120</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>20 minutes (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{140 minutes is the same as&nbsp; 2 hr. 20 min.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{2 hr. 20 min. is simplified because the number of hours (2) is less than the 24 hours that make a day and 20 minutes is less than the 60 minutes that make an hour.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>60 sec</td><td>=</td><td>1 min</td></tr><tr><td>60 min</td><td>=</td><td>1 hr</td></tr><tr><td>24 hr</td><td>=</td><td>1 day</td><tr><td>7 days</td><td>=</td><td>1 wk</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 2
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; 80 hours.}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				problemNumber: '80',
				problemUnits: 'hours',
				firstAnswer: '3',
				firstField: 'days',
				secondAnswer: '8',
				secondField: 'hrs.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 24 hours = 1 day. $$problemNumber $$problemUnits is more units than make the next larger time measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide Divide 80 hours by 24 to find out how many \"days\" are in 80 hours.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;</span>3 days'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>24</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>$$problemNumber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>72</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>8 $$problemUnits (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{80 hours is the same as 3 days 8 hrs.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{3 days 8 hrs. is simplified because the number of hours (8) is less than the 24 hours that make a day.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>60 sec</td><td>=</td><td>1 min</td></tr><tr><td>60 min</td><td>=</td><td>1 hr</td></tr><tr><td>24 hr</td><td>=</td><td>1 day</td><tr><td>7 days</td><td>=</td><td>1 wk</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 3
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; 31 inches.}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				problemNumber: '31',
				problemUnits: 'inches',
				firstAnswer: '2',
				firstField: 'ft.',
				secondAnswer: '7',
				secondField: 'in.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 12 inches = 1 foot. 31 inches is more units than make the next larger length measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 31 inches by 12 to find out how many \"feet\" are in 31 inches.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;</span>2 feet'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>12</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>$$problemNumber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>24</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>7 $$problemUnits (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{31 inches is the same as 2 ft. 7 in.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{2 ft. 7 in. is simplified because the number of inches (7) is less than the 12 inches that make a foot.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>12 in</td><td>=</td><td>1 ft</td></tr><tr><td>3 ft</td><td>=</td><td>1 yd</td></tr><tr><td>5,280 ft</td><td>=</td><td>1 mi</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 4
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; 14,000 feet.}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				problemNumber: '14,000',
				problemUnits: 'feet',
				firstAnswer: '2',
				firstField: 'mi.',
				secondAnswer: '3440',
				secondField: 'ft.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 5,280 feet = 1 mile. 14,000 feet is more units than make the next larger length measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 14,000 feet by 5,280 to find out how many \"miles\" are in 14,000 feet.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;</span>2 miles'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>5280</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>$$problemNumber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>10560</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>3440 $$problemUnits (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{14,000 feet is the same as 2 mi. 3440 ft.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{2 mi. 3440 ft. is simplified because the number of feet (3440) is less than the 5280 feet that make a mile.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>12 in</td><td>=</td><td>1 ft</td></tr><tr><td>3 ft</td><td>=</td><td>1 yd</td></tr><tr><td>5,280 ft</td><td>=</td><td>1 mi</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 5
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; 62 ounces.}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				firstAnswer: '3',
				firstField: 'lbs.',
				secondAnswer: '14',
				secondField: 'oz.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 16 ounces = 1 pound. 62 ounces is more units than make the next larger weight measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 62 minutes by 16 to find out how many \"pounds\" are in 62 ounces.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;</span>3 pounds'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>16</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>62&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>48</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">&nbsp;</span>14 ounces (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{62 ounces is the same as&nbsp; 3 lbs. 14 oz.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{3 lbs. 14 oz. is simplified because the number of ounces (14) is less than the 16 ounces that make a pound.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>16 oz</td><td>=</td><td>1 lb</td></tr><tr><td>2000 lbs</td><td>=</td><td>1 ton</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 6
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; $$problemNumber $$problemUnits}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				problemNumber: '3260',
				problemUnits: 'pounds',
				firstAnswer: '1',
				firstField: 'ton',
				secondAnswer: '1260',
				secondField: 'lbs.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 2000 pounds = 1 ton. 3260 pounds is more units than make the next larger weight measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 3260 pounds by 2000 to find out how many \"tons\" are in 3260 pounds. }}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp;</span>1 ton'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>2000</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>$$problemNumber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>2000</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">&nbsp;</span>1260 pounds (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{3260 pounds is the same as 1 ton 1260 lbs.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{1 ton 1260 lbs. is simplified because the number of pounds (1260) is less than the 2000 pounds that make a ton.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>16 oz</td><td>=</td><td>1 lb</td></tr><tr><td>2000 lbs</td><td>=</td><td>1 ton</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 7
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\grp'
											+'{\\str{Simplify:&nbsp; $$problemNumber $$problemUnits}}'
										+'}'
										+'{\\html{&nbsp;}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
								+'}'
					),
				problemNumber: '19',
				problemUnits: 'teaspoons',
				firstAnswer: '6',
				firstField: 'tbsp.',
				secondAnswer: '1',
				secondField: 'tsp.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify a measurement, check to see if the number of given units is equal to or more than the number of those units which make a larger unit of measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case, 3 teaspoons = 1 tablespoon. 19 teaspoons is more units than make the next larger liquid volume measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 19 teaspoons by 3 to find out how many \"tablespoons\" are in 19 teaspoons.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;</span>6 tablespoons'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>3</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>$$problemNumber&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>18</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">&nbsp;&nbsp;&nbsp;</span>1 teaspoon (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{19 teaspoons is the same as 6 tbsp. 1 tsp.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{6 tbsp. 1 tsp. is simplified because the number of teaspoons (1) is less than the 3 teaspoons that make a tablespoon.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>3 tsp</td><td>=</td><td>1 tbsp</td></tr><tr><td>2 tbsp</td><td>=</td><td>1 fl oz</td></tr><tr><td>8 fl oz</td><td>=</td><td>1 c</td></tr><tr><td>2 c</td><td>=</td><td>1 pt</td></tr><tr><td>2 pt</td><td>=</td><td>1 qt</td></tr><tr><td>4 qt</td><td>=</td><td>1 gal</td></tr></table>}'),
				template: 'flexy'
			}
			,
			// problem 17
			{	
				stateProblem: dataUtils.pre(
									'\\rowgrp'
										+'{\\str{Simplify:}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{5 yards  4 feet  40 inches}}'
								),
				solution: dataUtils.pre(
							'\\rowgrp'
								+'{\\grp'
									+'{\\input{$$firstAnswer}}'
									+'{\\str{&nbsp;$$firstField&nbsp;&nbsp;}}'
									+'{\\input{$$secondAnswer}}'
									+'{\\str{&nbsp;$$secondField}}'
									+'{\\input{$$thirdAnswer}}'
									+'{\\str{&nbsp;$$thirdField}}'
								+'}'
					),
				firstAnswer: '7',
				firstField: 'yd.',
				secondAnswer: '1',
				secondField: 'ft.',
				thirdAnswer: '4',
				thirdField: 'in.',
				firstLines: dataUtils.pre(
									'{\\str{To simplify an expression which has more than one given unit of measurement, <u>always start with the smallest unit of measurement first</u>.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{In this case \"inches\" is the smallest unit of measurement. Can it be simplified?}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{12 inches = 1 foot. 40 inches is more units than make the next larger length measurement.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #1: Divide 40 inches by 12 to find out how many \"feet\" are in 40 inches:}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;</span>3 feet'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>12</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>40&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>36</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-&nbsp;&nbsp;</span>4 inches (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{40 inches is the same as 3 ft. 4 in.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'5 yards'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'4 feet'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>40 inches</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'3 feet'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'4 inches'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=4>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=3 class=continuedDecimal>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'5 yards'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'7 feet'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'4 inches'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{The inches (4) are now simplified because they are less than the 12 inches that make a foot.}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{Step #2: Now we need to simplify 7 feet because it is more than the 3 feet that make a yard. Divide 7 feet by 3 to find out how many \"yards\" are in 7 feet.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="hiddenSpace">&nbsp;&nbsp&nbsp;&nbsp;</span>2 yards'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=divisorstyleSmall>3</span>'
												+'</td>'
												+'<td>'
													+'<span class=dividendstyleSmall><span class="hiddenSpace">&nbsp;&nbsp;</span>7&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=bigger>-</span><span class=bottomBlackPadded>6</span>'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
												+'</td>'
												+'<td class=divisionPadTop>'
													+'<span class="bigger hiddenSpace">-</span>1 foot (now simplified)'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{7 feet is the same as&nbsp; 2 yd. 1 ft.}}'
									+'{\\str{&nbsp;}}'
									+'{\\html{'
										+'<table>'
											+'<tr>'
												+'<td>'
													+'Therefore:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'5 yards'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class=line_through>7 feet</span>'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'4 inches'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'<span class="bigger rotate-45-clockwise">|</span>&nbsp;&nbsp;<span class=fontweightBold>|</span>'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td class=textAlignRight>'
													+'+'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'2 yards'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'1 foot'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr class=lineheight40>'
												+'<td colspan=2>'
													+'&nbsp;'
												+'</td>'
												+'<td colspan=5 class=continuedDecimal>'
													+'&nbsp;'
												+'</td>'
											+'</tr>'
											+'<tr>'
												+'<td>'
													+'Becomes:'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'7 yards'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'1 foot'
												+'</td>'
												+'<td>'
													+'&nbsp;'
												+'</td>'
												+'<td>'
													+'4 inches'
												+'</td>'
											+'</tr>'
										+'</table>'
									+'}}'
									+'{\\str{&nbsp;}}'
									+'{\\str{7 yd.  1 ft.  4 in. is simplified because the number of feet (1) is less than the 3 feet that make a yard and 4 inches is less than the 12 inches that make an hour.}}'
								),
				helpAnswer: dataUtils.pre(
								'\\grp'
									+'{\\str{$$firstAnswer&nbsp;$$firstField&nbsp;&nbsp;$$secondAnswer&nbsp;$$secondField&nbsp;&nbsp;$$thirdAnswer&nbsp;$$thirdField}}'
					),
				modalChart: dataUtils.pre('\\html{<table class=equivalence-table><th colspan="3">Equivalence Table</th><tr><td>12 in</td><td>=</td><td>1 ft</td></tr><tr><td>3 ft</td><td>=</td><td>1 yd</td></tr><tr><td>5,280 ft</td><td>=</td><td>1 mi</td></tr></table>}'),
				template: 'flexy'
			}
        ];
		/*shuffle = [
				{ problems: [1,2], total: 1},
				{ problems: [3,4], total: 1},
				{ problems: [5,6], total: 1},
				{ problems: [7,8], total: 1},
				{ problems: [9,10], total: 1},
				{ problems: [11,12], total: 1},
				{ problems: [13,14], total: 1},
				{ problems: [15,16], total: 1},
				{ problems: [17,18], total: 1},
				{ problems: [19,20], total: 1}
		];
    
    	return dataUtils.build(desc, template, data, shuffle);*/
		
		return dataUtils.build(desc, template, data);
}]);
