/*global angular */

angular.module('mathSkills').service('data_dd_2', ['dataUtils', function (dataUtils) {
    var desc = {
			title: 'DD.2 Solving Algebraic Equations (Eliminating Fractions)',
    		path: 'dd.2-solving-algebraic-equations-eliminating-fractions',
            children: []
        },
	        template = {
			
			flexy: {
                title: 'Solving Algebraic Equations (Eliminating Fractions))',
                children: [{
                    title: 'Main Answer',
                    children: [{
						problem: '\\rowgrp'
										+'{\\html{$probQuestion}}'
										+'{\\html{&nbsp;}}'
										+'{$$probStatement}'
										,
						answer: '$solution',
						controls: {
								"checkAnswer": true,
								"help": '\\rowgrp' 	 
											+'$firstTable'
											+'{\\html{&nbsp;}}'
											+'{\\html{&nbsp;}}'
											+'{css'
												+'{\\grp'
													+'{\\str{Answer: &nbsp;}}'
													+'{$helpAnswer}'
												+'}'
												+'{help-answer-text}'
											+'}'
											+'{\\html{&nbsp;}}'
						}
					}]
				}]
			}
        },
        data = [
				{	// problem 11
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2x}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{5}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					ansVariable: 'x',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>6</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2x}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>6</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{5}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{4x + 3 = 5}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{4x + 3 - <strong>3</strong> = 5 - <strong>3</strong>}}'
						),
					helpFourthPiece: '4x = 2',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{4x}}'
												+'{\\str{<strong>4</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{<strong>4</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;x}}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\input{1}}'
														+'{\\input{2}}'
													+'}'
													+'{}'
												+'}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 6.&nbsp; 6 is the lowest number that all the denominators (3, 2, and 6) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 6 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 6.}}'
												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Subtract 3.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by 4.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					template: 'flexy',
				}
				,
				{	// problem 12
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3m}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{10}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{5}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					ansVariable: 'm',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>20</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3m}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{10}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>20</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{5}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{15m + 2 = 8}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{15m + 2 - <strong>2</strong> = 8 - <strong>2</strong>}}'
						),
					helpFourthPiece: '15m = 6',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{15m}}'
												+'{\\str{<strong>15</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{6}}'
												+'{\\str{<strong>15</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;x}}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{6}}'
												+'{\\str{15}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\input{2}}'
														+'{\\input{5}}'
													+'}'
													+'{}'
												+'}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 20.&nbsp; 20 is the lowest number that all the denominators (4, 10, and 5) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 20 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 20.}}'
												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Subtract 2.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by 15.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{5}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					template: 'flexy',
				}
				,
				{	// problem 13
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-1x&nbsp;}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-2&nbsp;}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					ansVariable: 'x',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>12</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-1x&nbsp;}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{+}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>12</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-2&nbsp;}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{-2x + 9 = -8}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{-2x + 9 - <strong>9</strong> = -8 - <strong>9</strong>}}'
						),
					helpFourthPiece: '-2x = -17',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-2x&nbsp;}}'
												+'{\\str{<strong>-2&nbsp;</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-17&nbsp;}}'
												+'{\\str{<strong>-2&nbsp;</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;x}}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{17}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\input{17}}'
														+'{\\input{2}}'
													+'}'
													+'{}'
												+'}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 12.&nbsp; 12 is the lowest number that all the denominators (6, 4, and 3) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 12 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 12.}}'
												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Subtract 9.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by -2.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{17}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					template: 'flexy',
				}
				,

				{	// problem 14
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-3a&nbsp;}}'
												+'{\\str{8}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{-}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					ansVariable: 'a',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>8</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-3a&nbsp;}}'
												+'{\\str{8}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{-}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>8</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{-3a - 2 = 4}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{-3a - 2 + <strong>2</strong> = 4 + <strong>2</strong>}}'
						),
					helpFourthPiece: '-3a = 6',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{-3a&nbsp;}}'
												+'{\\str{<strong>-3&nbsp;</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{&nbsp;6&nbsp;}}'
												+'{\\str{<strong>-3&nbsp;</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;a = -2}}'
										/*+'{\\css'
											+'{\\frac'
												+'{\\str{17}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'*/
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\input{-2}}'
												/*+'{\\css'
													+'{\\frac'
														+'{\\input{17}}'
														+'{\\input{2}}'
													+'}'
													+'{}'
												+'}'*/
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 8.&nbsp; 8 is the lowest number that all the denominators (8, 4, and 2) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 8 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 8.}}'
												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Add 2.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by -3.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = -2}}'
										/*+'{\\css'
											+'{\\frac'
												+'{\\str{17}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'*/
						),
					template: 'flexy',
				}
				,
				{	// problem 15
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3x}}'
												+'{\\str{10}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{-}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = 5}}'
						),
					ansVariable: 'x',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>30</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3x}}'
												+'{\\str{10}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{-}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{2}}'
												+'{\\str{3}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>30</strong> * ( 5 )}}'
										/*+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{2}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'*/
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{9x - 20 = 150}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{9x - 20 + <strong>20</strong> = 150 + <strong>20</strong>}}'
						),
					helpFourthPiece: '9x = 170',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{9x}}'
												+'{\\str{<strong>9</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{170}}'
												+'{\\str{<strong>9</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;x = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{170}}'
												+'{\\str{9}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\input{170}}'
														+'{\\input{9}}'
													+'}'
													+'{}'
												+'}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 30.&nbsp; 30 is the lowest number that all the denominators (10, 3, and 1) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 30 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 30.}}'
												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Add 20.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by 9.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{170}}'
												+'{\\str{9}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					template: 'flexy',
				}
				,
				{	// problem 16
					probQuestion: 'Solve for the value of the variable, or click &quot;no solution&quot; if the equation cannot be solved:',
					probStatement: dataUtils.pre(
									'\\grp'
										
										+'{\\str{2m - }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					ansVariable: 'm',
					helpFirstPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{<strong>12</strong>}}'
										+'{\\str{(}}'
										+'{\\str{2m -}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{3}}'
												+'{\\str{4}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
										+'{\\str{ = }}'
										+'{\\str{<strong>12</strong>}}'
										+'{\\str{(}}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{1}}'
												+'{\\str{6}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{)}}'
						),
					helpSecondPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{24m - 9 = 2}}'
						),
					helpThirdPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{24m - 9 + <strong>9</strong> = 2 + <strong>9</strong>}}'
						),
					helpFourthPiece: '24m = 11',
					helpFifthPiece: dataUtils.pre(
									'\\grp'
										+'{\\css'
											+'{\\frac'
												+'{\\str{24m}}'
												+'{\\str{<strong>24</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
										+'{\\str{ = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{11}}'
												+'{\\str{<strong>24</strong>}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					helpSixthPiece: dataUtils.pre(
									'\\grp'
										+'{\\str{&nbsp;m = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{11}}'
												+'{\\str{24}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					solution: dataUtils.pre(
								'\\pan{3}{9}'			
									+'{\\css'
										+'{\\rowgrp'
											+'{\\grp'
												+'{\\str{$$ansVariable = }}'
												+'{\\css'
													+'{\\frac'
														+'{\\input{11}}'
														+'{\\input{24}}'
													+'}'
													+'{}'
												+'}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\css'
												+'{\\str{or}}'
												+'{label_like fontsize125}'
											+'}'
											+'{\\html{&nbsp;}}'
											+'{\\btn{no solution}{F}{btn-primary}}'
										+'}'
										+'{marginLeft132px width140 textAlignCenter}'
									+'}'
						),
					firstTable: dataUtils.pre(
										'{\\html{&nbsp;}}'
										+'{\\str{<u>One</u> way to solve this problem is to eliminate all the fractions. We do this by multiplying <u><strong>every term on both sides of the equation</strong></u> by the lowest common denominator (LCD) of all the terms.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{The LCD in this equation is 12.&nbsp; 12 is the lowest number that all the denominators (2, 4, and 6) can divide into evenly.}}'
										+'{\\html{&nbsp;}}'
										+'{\\str{Multiply or distribute 12 to every term. Notice that all existing terms on each side of the equation have been put into a parenthesis to show this multiplication.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{Original equation:}}'
												+'{width180}'
											+'}'
											+'{$$probStatement}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{1<sup>st</sup>: &nbsp;Distribute the 12.}}'

												+'{width180}'
											+'}'
											+'{$$helpFirstPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class=fontsize125>&nbsp;</span>Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSecondPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\str{We can now <u>isolate the variable</u> because it is on one side of the equation <strong>only</strong>.}}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{2<sup>nd</sup>:&nbsp; Add 9.}}'
												+'{width180}'
											+'}'
											+'{$$helpThirdPiece}'
										+'}'
										+'{\\html{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{\\str{&nbsp;$$helpFourthPiece}}'
										+'}'
										
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{3<sup>rd</sup>: &nbsp;&nbsp;Divide by 24.}}'
												+'{width180}'
											+'}'
											+'{$$helpFifthPiece}'
										+'}'
										+'{\\str{&nbsp;}}'
										+'{\\grp'
											+'{\\css'
												+'{\\str{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Result:}}'
												+'{width180}'
											+'}'
											+'{$$helpSixthPiece}'
										+'}'
								),
					helpAnswer: dataUtils.pre(
									'\\grp'
										+'{\\str{<span class=fontsize110>$$ansVariable</span> = }}'
										+'{\\css'
											+'{\\frac'
												+'{\\str{11}}'
												+'{\\str{24}}'
											+'}'
											+'{fracNoMargin}'
										+'}'
						),
					template: 'flexy',
				}
        ];
		/*shuffle = [
				{ problems: [1,2], total: 1},
				{ problems: [3,4], total: 1},
				{ problems: [5,6], total: 1},
				{ problems: [7,8], total: 1},
				{ problems: [9,10], total: 1},
				{ problems: [11,12], total: 1},
				{ problems: [13,14], total: 1},
				{ problems: [15,16], total: 1},
				{ problems: [17,18], total: 1},
				{ problems: [19,20], total: 1},
				{ problems: [21,22], total: 1},
				{ problems: [23,24], total: 1}
		];
    
    	return dataUtils.build(desc, template, data, shuffle);*/
		
		return dataUtils.build(desc, template, data);
}]);
